### PR TITLE
Fix btrfs-tool version check

### PR DESCRIPTION
**Pull request by bitwiseman**
Tweak Docker version check regex and reuse that.

I have signed the CLA.

### CODE REVIEW

**Comment by bitwiseman** [comment]
Oh, I see #69 is pretty extensive and covers this.  Your choice as to which to take.

**Comment by jdoliner** [comment]
Since this one's ready to go now I'm going to merge it in.

Many thanks! If you drop me a line at jd@pachyderm.io with your tshirt size I'll get you some swag.

**Comment by peter-edge** [comment]
Hey, mines ready too! :) haha

**Comment by jdoliner** [comment]
Oh, didn't realize that :p. I'll get that merged in as well.

**Pull request merged**
