### PR TITLE
use golang 1.4 as base image

### PR DESCRIPTION
**Pull request by Mistobaan**
Unless Ubuntu has something strictly necessary for pfs...

### CODE REVIEW

**Comment by peter-edge** [comment]
I definitely default to golang:1.4.2 in general for these scenarios, but given that pachyderm does have some reliance on the host, i think being explicit about the OS might make sense? @jdoliner

**Comment by jdoliner** [comment]
In general I like golang:1.4.2 as a default. In this case size is really important though we want our main pfs container to be as small as possible.

Is there a good way to get it small and still use the official golang images? I feel like I remember trying out this pull and seeing a pretty big image.

**Comment by peter-edge** [comment]
Ya so my hope in the next few months is we don't have a reliance on anything in the actual image other than built binaries, but this will take a lot of work. The official golang images are based on debian I believe. I think for now it's six one way, half dozen the other. @Mistobaan thoughts?

**Comment by peter-edge** [comment]
We did this in the next branch, closing for now. Thanks for contributing/this was a good thought!

**Pull request closed without merging**
