### PR TITLE
Fixing btrfs-tool version check to at least version 3.14

### PR DESCRIPTION
**Pull request by DimShadoWWW**

### CODE REVIEW

**Comment by bitwiseman** [comment]
This will break for `3.20`.

**Comment by bitwiseman** [comment]
Assuming you want `> 3.14`, this should do it: 
`3\.((1[4-9])|([2-9][0-9])|([1-9][0-9][0-9]+))(\.[0-9]+)?`

**Comment by jdoliner** [comment]
@bitwiseman we do indeed want `> 3.14`. So I think what you have here is correct.

@DimShadoWWW would you mind signing our [CLA](https://pachyderm.wufoo.com/forms/pachyderm-contributor-license-agreement/)?

**Comment by jdoliner** [comment]
@DimShadoWWW did you get a chance to look at the [CLA](https://pachyderm.wufoo.com/forms/pachyderm-contributor-license-agreement/)

**Comment by bitwiseman** [comment]
Closable.

**Comment by peter-edge** [comment]
@bitwiseman @jdoliner should we close this and concentrate on https://github.com/pachyderm/pfs/pull/69? I'm all about 0 issues, 0 PRs :)

**Comment by jdoliner** [comment]
Yup, closing.

**Pull request closed without merging**
